name: Update Dependabot Alerts Overview

on:
  workflow_dispatch:
  schedule:
    - cron: "22 5 * * *"  # Daily at 05:22 UTC (~07:22 Europe/Zurich)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Build overview with Dependabot counts
        env:
          GH_TOKEN: ${{ secrets.SECURITY_READ_TOKEN }}
        run: |
          python scripts/build_overview.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Campus_Applications_Consolidated.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh Dependabot alert counts in overview"
            git push
          else
            echo "No changes to commit."
          fi
